version: '3.8'
services:
  # mongo:
  #   image: mongo
  #   restart: always
  #   ports:
  #     - "27017:27017"
  #   environment:
  #     - MONGO_INITDB_ROOT_USERNAME=root
  #     - MONGO_INITDB_ROOT_PASSWORD=example


  app_back:
    container_name: chat_app_back
    image: chat_app_back:0.0.1
    build:
      context: ./back-chat-app/
    ports:
      - "3005:443"
    # depends_on:
    #   - mongo
    environment:
      - PORT=443
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=example
      - DATABASE_URL=mongodb://root:example@mongo:27017/
      - DECODE_TOKEN=123456
      - TIME_TOKEN=1d


  app_client:
    container_name: chat_app_client
    image: chat_app_client:0.0.1
    build:
      context: ./client-chat-app/
    ports:
      - "3004:8080"
    depends_on:
      # - mongo
      - app_back
    environment:
      - PORT=8080
      - GRAPHQL_URI_SUB="ws://0.0.0.0:3005/graphql/subscriptions"
      - GRAPHQL_URI="http://0.0.0.0:3005/graphql"
      - VITE_BASE_URL="http://0.0.0.0:3004"
